name: publish-main

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.REGISTRY_TOKEN}}
      - name: Build & publish image
        run: |
          export REPO=$(sed 's/\(.*\)/\L\1/' <<< $GITHUB_REPOSITORY)
          docker build . -t ghcr.io/$REPO:main
          docker push ghcr.io/$REPO:main
