name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    permissions:
      packages: write
      contents: read
    steps:
      - name: Get Tag Info
        id: info
        run: |
          export RAWVERSION=${{ github.event.release.tag_name }}
          if [ $RAWVERSION = "" ]; then RAWVERSION="v0.0.0"; fi
          echo "version=$(sed 's/^.//' <<< $RAWVERSION)" >> $GITHUB_OUTPUT
          echo "repo=$(sed 's/\(.*\)/\L\1/' <<< $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT
          echo "time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Check-out
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.info.outputs.repo }}:latest,ghcr.io/${{ steps.info.outputs.repo }}:${{ steps.info.outputs.version }}

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.info.outputs.repo }}:main,ghcr.io/${{ steps.info.outputs.repo }}:${{ steps.info.outputs.time }}
