name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@v4
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.16.0
        with:
          java-version: 21
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: planningpoker.jar
          path: target/Planning-Poker*.jar
          retention-days: 90
